CREATE table USERS (
	ID VARCHAR2(12) PRIMARY KEY,
	PASSWORD VARCHAR2(12) NOT NULL,
	NAME VARCHAR2(30) NOT NULL,
	ROLE VARCHAR2(6) NOT NULL
);

INSERT INTO USERS(ID, PASSWORD, NAME, ROLE)
VALUES ('GUEST', 'GUEST123', '관리자', 'USER');

INSERT INTO USERS(ID, PASSWORD, NAME, ROLE)
VALUES ('ADMIN', 'ADMIN123', '관리자', 'ADMIN');

INSERT INTO USERS(ID, PASSWORD, NAME, ROLE)
VALUES ('MEMBER', 'MEMBER123', '일반회원', 'USER');

COMMIT

SELECT * FROM USERS;
